robot:
  variant: g1_29dof

policy:
  format: beyondmimic
  use_onnx_metadata: true
  use_estimator: true

control:
  policy_frequency: 50
  sim_frequency: 500
  kd_damp: 8.0

safety:
  tilt_check: false
  joint_position_limits: false

network:
  domain_id: 1
